### PR TITLE
Drop the call kind runtime argument

### PR DESCRIPTION
**Pull request by chfast**

### CODE REVIEW

**Comment by axic** [comment]
Is it such a big speed bump its worth the code duplication (in the binary)?

It doesn't matter for compiling to C, but it could if we actually manage compiling it to Wasm. However it is minor I suppose.

**Comment by axic** [comment]
Couldn't you merge delegatecall/staticcall into call now with `if constexpr` ?

**Comment by chfast** [comment]
This is only done for removing this additional immediate value. I don't have any benchmarks for calls. There is a way to de-duplicate the code again (and for all other calls) by using a proxy function. But I want to keep the information about the call kind effectively in the function pointer.

```
template <kind>
void op_call(...)
{
    op_call_impl(kind, ...);
}
```

**Comment by chfast** [comment]
> Couldn't you merge delegatecall/staticcall into call now with `if constexpr` ?

I could if I had more time. https://github.com/ethereum/evmone/issues/160

**Comment by chfast** [comment]
I'm merging this leaving the mentioned issues for later discussion and future work.

**Pull request merged**
