### PR TITLE
Test for EIP-663 with jumpdest

### PR DESCRIPTION
**Pull request by gumb0**
I've added a test on top of [EIP-663 implementation](https://github.com/ethereum/evmone/pull/98) for the problem called out by @chriseth in https://ethereum-magicians.org/t/eip-663-unlimited-swap-and-dup-instructions/3346/10

Basically some JUMPDESTs that were considered valid before EIP-663, with it are considered a part of the multibyte opcode and not a JUMPDEST. So some old contracts might be broken.

### CODE REVIEW

**Comment by chfast** [comment]
Can you extract your tests from this PR to merge them?

**Comment by gumb0** [comment]
@chfast They can't be merged to `master`, because they use `OP_SWAPSN`

**Comment by chfast** [comment]
> @chfast They can't be merged to `master`, because they use `OP_SWAPSN`

Just use `"b0"`, `"b1"` hex invalid opcodes.

**Comment by chfast** [comment]
Can I close this?

**Comment by gumb0** [comment]
> Can I close this?

Fine by me.

**Comment by chfast** [comment]
Obsolete.

**Pull request closed without merging**
