### PR TITLE
Import snailtracer benchmark

### PR DESCRIPTION
**Pull request by axic**
From https://github.com/axic/snailtracer/tree/10a0f4bbc2cf937e10c61992b6f0e368b32ff7f8,
but the constructor is removed.

### CODE REVIEW

**Comment by axic** [comment]
Do not merge yet, want to actually commit the changed sources to https://github.com/axic/snailtracer so we can refer to it.

**Comment by axic** [comment]
Rebased. Before merged, I'd still want to point the commit to a commithash in the source repo.

@chfast do you remember what else was blocking this?

**Comment by chfast** [comment]
```
-------------------------------------------------------------------------------------------------------------
Benchmark                                                   Time             CPU   Iterations UserCounters...
-------------------------------------------------------------------------------------------------------------
advanced/analyse/main/snailtracer_mean                   96.3 us         96.3 us           20 rate=184.084M/s size=17.73k
advanced/analyse/main/snailtracer_median                 96.3 us         96.3 us           20 rate=184.065M/s size=17.73k
advanced/analyse/main/snailtracer_stddev                0.059 us        0.059 us           20 rate=112.918k/s size=0
baseline/analyse/main/snailtracer_mean                   12.6 us         12.6 us           20 rate=1.4106G/s size=17.73k
baseline/analyse/main/snailtracer_median                 12.6 us         12.6 us           20 rate=1.41027G/s size=17.73k
baseline/analyse/main/snailtracer_stddev                0.066 us        0.066 us           20 rate=7.41335M/s size=0
advanced/execute/main/snailtracer/benchmark_mean        51780 us        51779 us           20 gas_rate=4.44572G/s gas_used=230.193M
advanced/execute/main/snailtracer/benchmark_median      51735 us        51734 us           20 gas_rate=4.44951G/s gas_used=230.193M
advanced/execute/main/snailtracer/benchmark_stddev        208 us          208 us           20 gas_rate=17.5997M/s gas_used=0
baseline/execute/main/snailtracer/benchmark_mean        44518 us        44518 us           20 gas_rate=5.17079G/s gas_used=230.193M
baseline/execute/main/snailtracer/benchmark_median      44520 us        44520 us           20 gas_rate=5.1706G/s gas_used=230.193M
baseline/execute/main/snailtracer/benchmark_stddev       17.0 us         17.0 us           20 gas_rate=1.98M/s gas_used=0
advanced/total/main/snailtracer/benchmark_mean          57670 us        57669 us           20 gas_rate=3.99168G/s gas_used=230.193M
advanced/total/main/snailtracer/benchmark_median        57687 us        57687 us           20 gas_rate=3.9904G/s gas_used=230.193M
advanced/total/main/snailtracer/benchmark_stddev          263 us          263 us           20 gas_rate=18.0965M/s gas_used=0
baseline/total/main/snailtracer/benchmark_mean          45215 us        45215 us           20 gas_rate=5.09119G/s gas_used=230.193M
baseline/total/main/snailtracer/benchmark_median        45166 us        45167 us           20 gas_rate=5.09653G/s gas_used=230.193M
baseline/total/main/snailtracer/benchmark_stddev          210 us          210 us           20 gas_rate=23.2184M/s gas_used=0
```

The gas_rate is screwed  because a lot of EVM memory is used.

**Review by chfast — APPROVED** [review]

**Comment by chfast** [comment]
Done in https://github.com/ipsilon/evm-benchmarks/pull/12.

**Pull request closed without merging**
