### PR TITLE
eof: Add missing `RJUMPV` undefined in legacy test

### PR DESCRIPTION
**Pull request by chfast**

### CODE REVIEW

**Review by pdobacz — APPROVED** [review]
lgtm - just a nitpick - the other test groups RJUMP and RJUMPI together, maybe better decide to either split or group together all 3?

**Comment by chfast** [comment]
> lgtm - just a nitpick - the other test groups RJUMP and RJUMPI together, maybe better decide to either split or group together all 3?

I though maybe looping over all unavailable opcodes is enough but noticed these tests have some meaningful code and also are spread around. Up for grabs I think.

**Comment by pdobacz** [comment]
> > lgtm - just a nitpick - the other test groups RJUMP and RJUMPI together, maybe better decide to either split or group together all 3?
> 
> I though maybe looping over all unavailable opcodes is enough but noticed these tests have some meaningful code and also are spread around. Up for grabs I think.

Not sure I understand your reply. What I've meant is to either have:

 - `rjumps_undefined_in_legacy` with all 3 together or
 - `rjump[iv]_undefined_in_legacy` with all 3 separate

so it's a tiny bit easier to see what is and what isn't tested.

**Comment by chfast** [comment]
> > > lgtm - just a nitpick - the other test groups RJUMP and RJUMPI together, maybe better decide to either split or group together all 3?
> > 
> > 
> > I though maybe looping over all unavailable opcodes is enough but noticed these tests have some meaningful code and also are spread around. Up for grabs I think.
> 
> Not sure I understand your reply. What I've meant is to either have:
> 
>     * `rjumps_undefined_in_legacy` with all 3 together or
> 
>     * `rjump[iv]_undefined_in_legacy` with all 3 separate
> 
> 
> so it's a tiny bit easier to see what is and what isn't tested.

Ok, make sense.

**Pull request merged**
