### PR TITLE
tracing: Separate gas parameter

### PR DESCRIPTION
**Pull request by chfast**
Decouple "gas left" from ExecutionState and pass it as separate param.

### CODE REVIEW

**Comment by axic** [comment]
What is the motivation?

**Comment by chfast** [comment]
We are going to remove `gas_left` from `ExecutionState` in next PR.

**Comment by chfast** [comment]
See continuation in #600.

**Comment by rodiazet** [comment]
`state.gas_left` is used also in a couple of different places in the code. Are you going to separate it in additional PRs?

**Comment by chfast** [comment]
> See continuation in #600.

**Review by gumb0 — APPROVED** [review]

**Pull request merged**
